apiVersion: v1
kind: Service
metadata:
  name: books-api-service
spec:
  type: NodePort
  selector:
    app: books-api
  ports:
  - protocol: TCP
    port: 8084      # Internal Kubernetes port
    targetPort: 8084 # Maps to container's port
    nodePort: 30000 # External port accessible from browser